import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS
import "./globals.css"; // Import your global styles

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='container'>
          <div className='wrapper'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
